# Default configuration file for JounceBot
#   Copy this:( I' and place in either the JounceBot root or /etc as jouncebot.yaml

irc:
  server: chat.freenode.net
  port: 6697
  channel: "#wikimedia-operations"
  nick: jouncebot
  realname: "https://wikitech.wikimedia.org/wiki/Tool:Jouncebot"
  password: SecretSauce

mwclient:
  wiki: wikitech.wikimedia.org
  calPage: Deployments

aclFile: /etc/jouncebot.acl.yaml

logging:
  useSyslog: no

messages:
  generic:
    - 'Deploy window {event.window} ({event.url})'
  deployer:
    - '{deployers}: Dear anthropoid, the time has come. Please deploy {event.window} ({event.url}).'
    - '{deployers}: Respected human, time to deploy {event.window} ({event.url}). Please do the needful.'
  owner:
    - '{owners}: A patch you scheduled for {event.window} is about to be deployed. Please be available during the process.'

debug: false
