# Default configuration file for JounceBot
#   Copy this:( I' and place in either the JounceBot root or /etc as jouncebot.yaml

irc:
  server: chat.freenode.net
  port: 6697
  channel: "#wikimedia-operations"
  nick: jouncebot
  realname: "https://wikitech.wikimedia.org/wiki/Tool:Jouncebot"
  password: SecretSauce

mwclient:
  wiki: wikitech.wikimedia.org
  calPage: Deployments

aclFile: /etc/jouncebot.acl.yaml

logging:
  useSyslog: no

messages:
  generic:
    - 'Deploy window {event.window} ({event.url})'
  deployer:
    - '{deployers}: How many deployers does it take to do {event.window} deploy? ({event.url}).'
    - '{deployers}: Time to pull up your socks and deploy {event.window}. Get on with it. ({event.url}).'
    - '{deployers}: Dear deployers, time to do the {event.window} deploy. Dont look at me like that. You signed up for it. ({event.url}).'
    - '{deployers}: It is that lovely time of the day again! You are hereby commanded to deploy {event.window}. ({event.url}).'
    - '{deployers}: (Dis)respected human, time to deploy {event.window} ({event.url}). Please do the needful.'
  owner:
    - '{owners}: A patch you scheduled for {event.window} is about to be deployed. Please be around during the process. Note: If you break the wikis, you will be rewarded with a sticker.'

debug: false
